--------------------------------------------------------
--  파일이 생성됨 - 화요일-8월-08-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RATING_HISTORY
--------------------------------------------------------

  CREATE TABLE "SCOTT"."RATING_HISTORY" 
   (	"REVIEW_NUMBER" NUMBER(5,0), 
	"TALKING_SPEED" NUMBER(1,0), 
	"FRIENDLINESS" NUMBER(1,0), 
	"PRONUNCIATION" NUMBER(1,0), 
	"WORTHY_OF_CONTENT" NUMBER(1,0), 
	"PLEASURE" NUMBER(1,0), 
	"MENTOR_ID" VARCHAR2(12 BYTE), 
	"ID" VARCHAR2(12 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SCOTT.RATING_HISTORY
SET DEFINE OFF;
Insert into SCOTT.RATING_HISTORY (REVIEW_NUMBER,TALKING_SPEED,FRIENDLINESS,PRONUNCIATION,WORTHY_OF_CONTENT,PLEASURE,MENTOR_ID,ID) values (7,1,1,1,1,1,'a',null);
Insert into SCOTT.RATING_HISTORY (REVIEW_NUMBER,TALKING_SPEED,FRIENDLINESS,PRONUNCIATION,WORTHY_OF_CONTENT,PLEASURE,MENTOR_ID,ID) values (10,2,2,2,2,2,'a',null);
Insert into SCOTT.RATING_HISTORY (REVIEW_NUMBER,TALKING_SPEED,FRIENDLINESS,PRONUNCIATION,WORTHY_OF_CONTENT,PLEASURE,MENTOR_ID,ID) values (14,3,2,1,4,5,'b',null);
Insert into SCOTT.RATING_HISTORY (REVIEW_NUMBER,TALKING_SPEED,FRIENDLINESS,PRONUNCIATION,WORTHY_OF_CONTENT,PLEASURE,MENTOR_ID,ID) values (23,5,5,5,5,5,'e',null);
Insert into SCOTT.RATING_HISTORY (REVIEW_NUMBER,TALKING_SPEED,FRIENDLINESS,PRONUNCIATION,WORTHY_OF_CONTENT,PLEASURE,MENTOR_ID,ID) values (9,3,3,3,3,3,'b',null);
Insert into SCOTT.RATING_HISTORY (REVIEW_NUMBER,TALKING_SPEED,FRIENDLINESS,PRONUNCIATION,WORTHY_OF_CONTENT,PLEASURE,MENTOR_ID,ID) values (11,3,4,4,3,3,'a',null);
Insert into SCOTT.RATING_HISTORY (REVIEW_NUMBER,TALKING_SPEED,FRIENDLINESS,PRONUNCIATION,WORTHY_OF_CONTENT,PLEASURE,MENTOR_ID,ID) values (12,1,1,1,2,1,'c',null);
Insert into SCOTT.RATING_HISTORY (REVIEW_NUMBER,TALKING_SPEED,FRIENDLINESS,PRONUNCIATION,WORTHY_OF_CONTENT,PLEASURE,MENTOR_ID,ID) values (13,1,1,3,3,1,'c',null);
Insert into SCOTT.RATING_HISTORY (REVIEW_NUMBER,TALKING_SPEED,FRIENDLINESS,PRONUNCIATION,WORTHY_OF_CONTENT,PLEASURE,MENTOR_ID,ID) values (5,2,3,3,4,5,'c',null);
Insert into SCOTT.RATING_HISTORY (REVIEW_NUMBER,TALKING_SPEED,FRIENDLINESS,PRONUNCIATION,WORTHY_OF_CONTENT,PLEASURE,MENTOR_ID,ID) values (6,5,5,3,4,5,'d',null);
Insert into SCOTT.RATING_HISTORY (REVIEW_NUMBER,TALKING_SPEED,FRIENDLINESS,PRONUNCIATION,WORTHY_OF_CONTENT,PLEASURE,MENTOR_ID,ID) values (8,1,1,1,1,1,'d',null);
--------------------------------------------------------
--  DDL for Index RATING_HISTORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."RATING_HISTORY_PK" ON "SCOTT"."RATING_HISTORY" ("REVIEW_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table RATING_HISTORY
--------------------------------------------------------

  ALTER TABLE "SCOTT"."RATING_HISTORY" ADD CONSTRAINT "RATING_HISTORY_PK" PRIMARY KEY ("REVIEW_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
