--------------------------------------------------------
--  파일이 생성됨 - 화요일-8월-08-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MENTOR
--------------------------------------------------------

  CREATE TABLE "SCOTT"."MENTOR" 
   (	"ID" VARCHAR2(12 BYTE), 
	"NATION" VARCHAR2(20 BYTE), 
	"EDU_LANGUAGE1" VARCHAR2(20 BYTE), 
	"EDU_LANGUAGE2" VARCHAR2(20 BYTE), 
	"EDU_LANGUAGE3" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "SCOTT"."MEMBER" 
   (	"ID" VARCHAR2(12 BYTE), 
	"PASSWORD" VARCHAR2(64 BYTE), 
	"NAME" VARCHAR2(30 BYTE), 
	"NICKNAME" VARCHAR2(20 BYTE), 
	"BIRTH" VARCHAR2(8 BYTE), 
	"HP" VARCHAR2(13 BYTE), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"GENDER" VARCHAR2(3 BYTE), 
	"POINT" NUMBER(10,0) DEFAULT 0, 
	"GRADE_NUMBER" NUMBER(1,0) DEFAULT 1, 
	"PROFILEPICTURE" VARCHAR2(100 BYTE), 
	"INTRODUCEMYSELF" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SCOTT.MENTOR
SET DEFINE OFF;
REM INSERTING into SCOTT.MEMBER
SET DEFINE OFF;
Insert into SCOTT.MEMBER (ID,PASSWORD,NAME,NICKNAME,BIRTH,HP,EMAIL,GENDER,POINT,GRADE_NUMBER,PROFILEPICTURE,INTRODUCEMYSELF) values ('test','testtest','정해윤','1234','19911212','010-5468-0643','j508@naver.com','m',0,1,'4.PNG',null);
Insert into SCOTT.MEMBER (ID,PASSWORD,NAME,NICKNAME,BIRTH,HP,EMAIL,GENDER,POINT,GRADE_NUMBER,PROFILEPICTURE,INTRODUCEMYSELF) values ('admin','admin','admin','admin','19981212','010-1234-0643','aadmin@naber.com','f',500,3,null,null);
Insert into SCOTT.MEMBER (ID,PASSWORD,NAME,NICKNAME,BIRTH,HP,EMAIL,GENDER,POINT,GRADE_NUMBER,PROFILEPICTURE,INTRODUCEMYSELF) values ('test2','qwerqwer','정해윤','1234','19911212','010-1234-1234','jhs508@naver.com','m',0,1,null,null);
--------------------------------------------------------
--  DDL for Index SYS_C0011107
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C0011107" ON "SCOTT"."MENTOR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MENTOR
--------------------------------------------------------

  ALTER TABLE "SCOTT"."MENTOR" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
